package com.github.chengyuxing.sql.support;

import com.github.chengyuxing.common.DataRow;

import java.util.List;
import java.util.Map;
import java.util.stream.Stream;

/**
 * Query cache manager.
 */
public interface QueryCacheManager {
    /**
     * Unique key for the cache.
     * <p>It is necessary to ensure uniqueness to avoid cache clutter.</p>
     *
     * @param sql  sql name
     * @param args args
     * @return the unique key
     */
    String uniqueKey(String sql, Map<String, Object> args);

    /**
     * Get cache.
     * <p>Notice: Do not return an empty stream if the cache does not exist.
     * To trigger the execution of a database query, null must be returned.</p>
     *
     * @param uniqueKey unique cache key generated by {@link #uniqueKey(String, Map)}
     * @return cache or null
     */
    Stream<DataRow> get(String uniqueKey);

    /**
     * Put cache.
     *
     * @param uniqueKey unique cache key generated by {@link #uniqueKey(String, Map)}
     * @param value     query result
     */
    void put(String uniqueKey, List<DataRow> value);

    /**
     * Invalidate cache.
     *
     * @param sql  sql name
     * @param args args
     */
    default void invalidate(String sql, Map<String, Object> args) {
    }

    /**
     * Check the sql matches the conditions or not, if matches,
     * {@link #put(String, List) put} and {@link #get(String) get} will be enabling.
     *
     * @param sql  sql name
     * @param args params
     * @return true or false
     */
    boolean isAvailable(String sql, Map<String, Object> args);

}
