package com.github.chengyuxing.sql.plugins;

import org.jetbrains.annotations.NotNull;

import java.util.List;
import java.util.Map;
import java.util.function.Function;

/**
 * Simple sql builder executor.
 */
public interface SimpleDMLExecutor {
    /**
     * Enable JDBC batch execute statement, by default each item will generate one SQL in for loop to execute.
     * <p>Notice: SQL statement generated by 1st item of iterable, so even if 2nd item different with 1st item,
     * SQL statement always base on 1st item, especially the {@code insert} and {@code update} statement.</p>
     *
     * @return Simple DML Executor
     */
    SimpleDMLExecutor enableBatch();

    /**
     * Execute insert.
     *
     * @param data data
     * @return affected row count
     */
    int insert(@NotNull Map<String, ?> data);

    /**
     * Execute multiple insert, generate insert statement by args, e.g.
     * <p>Args: {@code {id:14, name:'cyx', address:'kunming'}}</p>
     * Generate:
     * <blockquote><pre>
     * insert into user (id, name, address) values (:id, :name, :address)
     * </pre></blockquote>
     *
     * @param data data
     * @return affected row count
     * @see SimpleDMLExecutor#enableBatch()
     */
    int insert(@NotNull Iterable<? extends Map<String, ?>> data);

    /**
     * Execute multiple insert.
     *
     * @param data      data
     * @param argMapper arg mapping to Map function
     * @param <T>       arg type
     * @return affected row count
     * @see #insert(Iterable)
     */
    <T> int insert(@NotNull Iterable<T> data, @NotNull Function<T, ? extends Map<String, ?>> argMapper);

    /**
     * Where conditional interface.
     *
     * @param condition condition e.g. id = :id
     * @return Conditional object
     */
    Conditional where(@NotNull String condition);

    /**
     * Execute query table fields.
     *
     * @return fields
     */
    List<String> fields();

    /**
     * The dml statement with where condition.
     */
    interface Conditional {
        /**
         * Execute update, generate update statement by args, e.g.
         * <p>Args: {@code {id:14, name:'cyx', address:'kunming'}}</p>
         * Where:
         * <blockquote><pre>
         *  id = :id
         * </pre></blockquote>
         * Generate:
         * <blockquote><pre>
         * update user set name = :name, address = :address where id = :id
         * </pre></blockquote>
         *
         * @param args all args which contains sets and conditional part
         * @return affected row count
         * @see SimpleDMLExecutor#enableBatch()
         */
        int update(@NotNull Map<String, ?> args);

        /**
         * Execute multiple update, generate update statement by args, e.g.
         * <p>Args: {@code {id:14, name:'cyx', address:'kunming'}}</p>
         * Where:
         * <blockquote><pre>
         *  id = :id
         * </pre></blockquote>
         * Generate:
         * <blockquote><pre>
         * update user set name = :name, address = :address where id = :id
         * </pre></blockquote>
         * <p>Notice: where condition must contain at least 1 named parameter and args must contain its value.</p>
         *
         * @param args all args which contains sets and conditional part
         * @return affected row count
         * @see SimpleDMLExecutor#enableBatch()
         */
        int update(@NotNull Iterable<? extends Map<String, ?>> args);

        /**
         * Execute multiple update.
         *
         * @param args      all args which contains sets and conditional part
         * @param argMapper arg mapping to Map function
         * @param <T>       arg type
         * @return affected row count
         * @see #update(Iterable)
         */
        <T> int update(@NotNull Iterable<T> args, @NotNull Function<T, ? extends Map<String, ?>> argMapper);

        /**
         * Execute delete.
         *
         * @param args args
         * @return affected row count
         */
        int delete(@NotNull Map<String, ?> args);

        /**
         * Execute batch delete.
         *
         * @param args args
         * @return affected row count
         */
        int delete(@NotNull Iterable<? extends Map<String, ?>> args);

        /**
         * Execute batch delete.
         *
         * @param args      args
         * @param argMapper arg mapping to Map function
         * @param <T>       arg type
         * @return affected row count
         */
        <T> int delete(@NotNull Iterable<T> args, @NotNull Function<T, ? extends Map<String, ?>> argMapper);
    }
}
