package com.github.chengyuxing.sql.dsl;

import com.github.chengyuxing.common.MethodReference;

/**
 * DSL insert operator.
 *
 * @param <T> entity type
 */
public interface Insert<T> {
    /**
     * Enabling insert's values allows setting null values,
     * by default insert statement set part will be excluded null values.
     * <p>Example: {@code {id: null, name: 'cyx', address: 'kunming'}}</p>
     * Enable:
     * <blockquote><pre>
     *     insert into user (id, name, address) values (:id, :name, :address)
     * </pre></blockquote>
     * Disable (default):
     * <blockquote><pre>
     *     insert into user (name, address) values (:name, :address)
     * </pre></blockquote>
     *
     * @return Insert object
     */
    Insert<T> withNullValues();

    /**
     * Insert.
     *
     * @param entity entity
     * @return affected row count
     * @see #withNullValues()
     */
    int save(T entity);

    /**
     * Multiple insert.
     *
     * @param entities entities
     * @return affected row count
     * @see #withNullValues()
     */
    int save(Iterable<T> entities);

    /**
     * Insert the specified columns and by default other columns generated by database default value.
     *
     * @param column column
     * @param value  value
     * @return InsertSetter
     */
    InsertSetter<T> set(MethodReference<T> column, Object value);

    /**
     * Insert's values builder.
     *
     * @param <T> entity type
     */
    interface InsertSetter<T> {
        /**
         * Add value ready to insert.
         *
         * @param column column
         * @param value  value
         * @return InsertSetter
         */
        InsertSetter<T> set(MethodReference<T> column, Object value);

        /**
         * Do insert save.
         *
         * @return affected row count
         */
        int save();
    }
}
